import React, { useState, useRef, useEffect } from "react";
import { createChart, ColorType, HistogramData, LineData, Time, IChartApi, ISeriesApi } from "lightweight-charts";

export interface TierMetrics {
    impressions: number; // Total views generated by this tier
    engagement: number; // Total weighted engagement score from this tier
    volume: number; // Number of tweets from this tier
}

export interface TieredInfluence {
    name: string; // Timestamp of the interval
    whale: TierMetrics;
    shark: TierMetrics;
    retail: TierMetrics;
}

type ZoomReport = {
    totalpage: number;
    currentpage: number;
};

interface TieredInfluenceChartProps {
    data: TieredInfluence[];
    funtype: string;
    onZoomOrPan?: (page: number, funtype: string) => Promise<ZoomReport>;
}

const TieredImpressionChart: React.FC<TieredInfluenceChartProps> = ({ 
    data, 
    funtype, 
    onZoomOrPan 
}) => {
    const chartContainerRef = useRef<HTMLDivElement>(null);
    const chartRef = useRef<IChartApi | null>(null);
    const whaleSeriesRef = useRef<ISeriesApi<"Histogram"> | null>(null);
    const sharkSeriesRef = useRef<ISeriesApi<"Histogram"> | null>(null);
    const retailSeriesRef = useRef<ISeriesApi<"Histogram"> | null>(null);
    const emaSeriesRef = useRef<ISeriesApi<"Line"> | null>(null);
    const velocitySeriesRef = useRef<ISeriesApi<"Line"> | null>(null);
    
    const [isLoaded, setIsLoaded] = useState(true);
    const [isEnd, setIsEnd] = useState(false);
    const [showWhale, setShowWhale] = useState(true);
    const [showShark, setShowShark] = useState(true);
    const [showRetail, setShowRetail] = useState(true);
    const [showEMA, setShowEMA] = useState(true);
    const [showVelocity, setShowVelocity] = useState(false);
    const [emaPeriod, setEmaPeriod] = useState(14);
    const [velocityPeriod, setVelocityPeriod] = useState(3);
    const [showEmaSettings, setShowEmaSettings] = useState(false);
    const [isPaused, setIsPaused] = useState(false);
    const [selectedMetric, setSelectedMetric] = useState<'impressions' | 'engagement' | 'volume'>('impressions');
    const [showMetricSettings, setShowMetricSettings] = useState(false);
    const pageRef = useRef(1);
    const totalPage = useRef(0);
    const throttleRef = useRef(false);

    // Calculate EMA
    const calculateEMA = (values: number[], period: number = 14): number[] => {
        const ema: number[] = [];
        const multiplier = 2 / (period + 1);
        
        if (values.length === 0) return ema;
        
        // First EMA is just the first value
        ema[0] = values[0];
        
        // Calculate subsequent EMAs
        for (let i = 1; i < values.length; i++) {
            ema[i] = (values[i] * multiplier) + (ema[i - 1] * (1 - multiplier));
        }
        
        return ema;
    };

    // Calculate EMA Velocity (rate of change)
    const calculateVelocity = (emaValues: number[], period: number = 3): number[] => {
        const velocity: number[] = [];
        
        for (let i = 0; i < emaValues.length; i++) {
            if (i < period) {
                velocity[i] = 0; // No velocity for initial periods
            } else {
                // Calculate rate of change over the specified period
                const change = emaValues[i] - emaValues[i - period];
                const timeSpan = period; // periods
                velocity[i] = change / timeSpan;
            }
        }
        
        return velocity;
    };

    console.log("data:", data);
    // Process data based on selected metric
    const processedData = React.useMemo(() => {
        const sortedData = [...data].sort((a, b) => new Date(a.name).getTime() - new Date(b.name).getTime());
        
        const whaleData: HistogramData[] = [];
        const sharkData: HistogramData[] = [];
        const retailData: HistogramData[] = [];
        const netChangeValues: number[] = [];
        
        let prevWhale = 0;
        let prevShark = 0;
        let prevRetail = 0;

        sortedData.forEach((item, index) => {
            const time = Math.floor(new Date(item.name).getTime() / 1000) as Time;

            // Get current values based on selected metric
            const currentWhale = item.whale[selectedMetric];
            const currentShark = item.shark[selectedMetric];
            const currentRetail = item.retail[selectedMetric];

            // Calculate net change per category
            const netWhale = currentWhale//index === 0 ? 0 : currentWhale - prevWhale;
            const netShark = currentShark//index === 0 ? 0 : currentShark - prevShark;
            const netRetail = currentRetail//index === 0 ? 0 : currentRetail - prevRetail;
            const netTotal = netWhale + netShark + netRetail;

            whaleData.push({
                time,
                value: netWhale,
                color: netWhale >= 0 ? '#3B82F6' : '#1E40AF'
            });

            sharkData.push({
                time,
                value: netShark,
                color: netShark >= 0 ? '#10B981' : '#059669'
            });

            retailData.push({
                time,
                value: netRetail,
                color: netRetail >= 0 ? '#F59E0B' : '#D97706'
            });

            netChangeValues.push(netTotal);

            prevWhale = currentWhale;
            prevShark = currentShark;
            prevRetail = currentRetail;
        });

        // Calculate EMA for net change values using the configurable period
        const emaValues = calculateEMA(netChangeValues, emaPeriod);
        const emaData: LineData[] = emaValues.map((value, index) => ({
            time: whaleData[index].time,
            value
        }));

        // Calculate velocity of EMA
        const velocityValues = calculateVelocity(emaValues, velocityPeriod);
        const velocityData: LineData[] = velocityValues.map((value, index) => ({
            time: whaleData[index].time,
            value
        }));
        
        return { whaleData, sharkData, retailData, emaData, velocityData };
    }, [data, emaPeriod, velocityPeriod, selectedMetric]);

    useEffect(() => {
        if (!chartContainerRef.current) return;

        // Create chart
        const chart = createChart(chartContainerRef.current, {
            width: chartContainerRef.current.clientWidth,
            height: chartContainerRef.current.clientHeight,
            layout: {
                background: { type: ColorType.Solid, color: 'transparent' },
                textColor: '#fff',
            },
            grid: {
                vertLines: { visible: false },
                horzLines: { visible: false, color: '#E5E7EB', style: 2 },
            },
            crosshair: {
                mode: 1,
            },
            rightPriceScale: {
                visible: true,
                borderVisible: false,
            },
            timeScale: {
                visible: true,
                borderVisible: false,
                timeVisible: true,
                secondsVisible: false,
            },
            handleScroll: {
                mouseWheel: false,
                pressedMouseMove: true,
                horzTouchDrag: true,
                vertTouchDrag: false,
            },
            handleScale: {
                axisPressedMouseMove: true,
                mouseWheel: true,
                pinch: true,
            },
        });

        // Create whale histogram series
        const whaleSeries = chart.addHistogramSeries({
            color: '#3B82F6',
            priceFormat: {
                type: 'volume',
            },
            visible: showWhale,
        });

        // Create shark histogram series
        const sharkSeries = chart.addHistogramSeries({
            color: '#10B981',
            priceFormat: {
                type: 'volume',
            },
            visible: showShark,
        });

        // Create retail histogram series
        const retailSeries = chart.addHistogramSeries({
            color: '#F59E0B',
            priceFormat: {
                type: 'volume',
            },
            visible: showRetail,
        });

        // Create EMA line series
        const emaSeries = chart.addLineSeries({
            color: '#EF4444',
            lineWidth: 2,
            crosshairMarkerVisible: true,
            crosshairMarkerRadius: 3,
            visible: showEMA,
        });

        // Create velocity line series (on separate price scale)
        const velocitySeries = chart.addLineSeries({
            color: '#8B5CF6',
            lineWidth: 2,
            crosshairMarkerVisible: true,
            crosshairMarkerRadius: 3,
            visible: showVelocity,
            priceScaleId: 'velocity',
        });

        // Configure separate price scale for velocity
        chart.priceScale('velocity').applyOptions({
            scaleMargins: {
                top: 0.8,
                bottom: 0,
            },
            borderVisible: false,
        });

        // Set data
        if (processedData.whaleData.length > 0) {
            whaleSeries.setData(processedData.whaleData);
        }
        if (processedData.sharkData.length > 0) {
            sharkSeries.setData(processedData.sharkData);
        }
        if (processedData.retailData.length > 0) {
            retailSeries.setData(processedData.retailData);
        }
        if (processedData.emaData.length > 0) {
            emaSeries.setData(processedData.emaData);
        }
        if (processedData.velocityData.length > 0) {
            velocitySeries.setData(processedData.velocityData);
        }

        // Store references
        chartRef.current = chart;
        whaleSeriesRef.current = whaleSeries;
        sharkSeriesRef.current = sharkSeries;
        retailSeriesRef.current = retailSeries;
        emaSeriesRef.current = emaSeries;
        velocitySeriesRef.current = velocitySeries;

        // Set initial visible range
        if (processedData.whaleData.length > 5) {
            const startIndex = Math.max(0, processedData.whaleData.length - 20);
            const endIndex = processedData.whaleData.length - 1;
            
            if (startIndex < processedData.whaleData.length && endIndex < processedData.whaleData.length) {
                chart.timeScale().setVisibleRange({
                    from: processedData.whaleData[startIndex].time,
                    to: processedData.whaleData[endIndex].time,
                });
            }
        }

        // Handle visible range changes for pagination
        chart.timeScale().subscribeVisibleTimeRangeChange(async (newVisibleTimeRange) => {
            if (!newVisibleTimeRange || !onZoomOrPan || isEnd || !isLoaded || throttleRef.current || isPaused) {
                return;
            }

            const startTime = newVisibleTimeRange.from as number;
            const startIndex = processedData.whaleData.findIndex(point => (point.time as number) >= startTime);
            
            if (startIndex < 2 && startIndex >= 0) {
                throttleRef.current = true;
                setIsLoaded(false);
                
                try {
                    console.log('Loading more data for page:', pageRef.current);
                    const report = await onZoomOrPan(pageRef.current, funtype);
                    console.log('Zoom/Pan report:', report);
                    
                    if (report.totalpage > 0) {
                        totalPage.current = report.totalpage;
                        if (report.totalpage > pageRef.current) {
                            pageRef.current = report.currentpage + 1;
                            console.log('Updated page to:', pageRef.current);
                        } else {
                            setIsEnd(true);
                            console.log('Reached end of data');
                        }
                        
                        setTimeout(() => {
                            setIsLoaded(true);
                            throttleRef.current = false;
                        }, 1000);
                    } else {
                        setIsLoaded(true);
                        setTimeout(() => {
                            throttleRef.current = false;
                        }, 500);
                    }
                } catch (error) {
                    console.error('Error in onZoomOrPan:', error);
                    setIsLoaded(true);
                    setTimeout(() => {
                        throttleRef.current = false;
                    }, 500);
                }
            }
        });

        // Handle resize
        const resizeObserver = new ResizeObserver(entries => {
            if (entries.length === 0 || entries[0].target !== chartContainerRef.current) {
                return;
            }
            const newRect = entries[0].contentRect;
            chart.applyOptions({ width: newRect.width });
        });

        if (chartContainerRef.current) {
            resizeObserver.observe(chartContainerRef.current);
        }

        return () => {
            resizeObserver.disconnect();
            chart.remove();
        };
    }, []);

    // Update chart data when props change
    useEffect(() => {
        if (whaleSeriesRef.current && sharkSeriesRef.current && retailSeriesRef.current && emaSeriesRef.current && velocitySeriesRef.current && processedData.whaleData.length > 0) {
            const currentVisibleRange = chartRef.current?.timeScale().getVisibleRange();
            
            whaleSeriesRef.current.setData(processedData.whaleData);
            sharkSeriesRef.current.setData(processedData.sharkData);
            retailSeriesRef.current.setData(processedData.retailData);
            emaSeriesRef.current.setData(processedData.emaData);
            velocitySeriesRef.current.setData(processedData.velocityData);
            
            if (currentVisibleRange && processedData.whaleData.length > 0) {
                setTimeout(() => {
                    if (chartRef.current && !isPaused) {
                        chartRef.current.timeScale().fitContent();
                    }
                }, 50);
            }
        }
    }, [data, processedData]);

    // Reset pagination state when data changes significantly
    useEffect(() => {
        if (data.length < 10) {
            pageRef.current = 1;
            totalPage.current = 0;
            setIsEnd(false);
        }
    }, [data.length]);

    // Toggle series visibility
    useEffect(() => {
        if (whaleSeriesRef.current) {
            whaleSeriesRef.current.applyOptions({ visible: showWhale });
        }
    }, [showWhale]);

    useEffect(() => {
        if (sharkSeriesRef.current) {
            sharkSeriesRef.current.applyOptions({ visible: showShark });
        }
    }, [showShark]);

    useEffect(() => {
        if (retailSeriesRef.current) {
            retailSeriesRef.current.applyOptions({ visible: showRetail });
        }
    }, [showRetail]);

    useEffect(() => {
        if (emaSeriesRef.current) {
            emaSeriesRef.current.applyOptions({ visible: showEMA });
        }
    }, [showEMA]);

    useEffect(() => {
        if (velocitySeriesRef.current) {
            velocitySeriesRef.current.applyOptions({ visible: showVelocity });
        }
    }, [showVelocity]);

    // Custom tooltip
    useEffect(() => {
        if (!chartRef.current || !chartContainerRef.current) return;

        const container = chartContainerRef.current;
        let tooltip: HTMLDivElement | null = null;

        const createTooltip = () => {
            tooltip = document.createElement('div');
            tooltip.style.cssText = `
                position: absolute;
                display: none;
                padding: 8px 12px;
                background: rgba(0, 0, 0, 0.8);
                color: white;
                border-radius: 4px;
                font-size: 12px;
                pointer-events: none;
                z-index: 1000;
                white-space: nowrap;
                max-width: 200px;
            `;
            container.appendChild(tooltip);
        };

        const showTooltip = (param: any) => {
            if (!tooltip) createTooltip();
            if (!tooltip || !param.time || !param.seriesData.size) {
                if (tooltip) tooltip.style.display = 'none';
                return;
            }

            const whaleData = param.seriesData.get(whaleSeriesRef.current);
            const sharkData = param.seriesData.get(sharkSeriesRef.current);
            const retailData = param.seriesData.get(retailSeriesRef.current);
            const emaData = param.seriesData.get(emaSeriesRef.current);
            const velocityData = param.seriesData.get(velocitySeriesRef.current);
            const time = new Date((param.time as number) * 1000);
            
            let tooltipContent = `<div style="margin-bottom: 4px;"><strong>${time.toISOString()}</strong></div>`;
            tooltipContent += `<div style="margin-bottom: 4px; font-size: 11px; color: #9CA3AF;">Metric: ${selectedMetric.charAt(0).toUpperCase() + selectedMetric.slice(1)}</div>`;
            
            if (whaleData && showWhale) {
                tooltipContent += `<div style="color: #3B82F6;">Whale: ${whaleData.value.toFixed(2)}</div>`;
            }
            
            if (sharkData && showShark) {
                tooltipContent += `<div style="color: #10B981;">Shark: ${sharkData.value.toFixed(2)}</div>`;
            }
            
            if (retailData && showRetail) {
                tooltipContent += `<div style="color: #F59E0B;">Retail: ${retailData.value.toFixed(2)}</div>`;
            }
            
            if (emaData && showEMA) {
                tooltipContent += `<div style="color: #EF4444;">EMA (${emaPeriod}): ${emaData.value.toFixed(2)}</div>`;
            }
            
            if (velocityData && showVelocity) {
                const velocityValue = velocityData.value;
                const velocityDirection = velocityValue > 0 ? '↗' : velocityValue < 0 ? '↘' : '→';
                const velocityIntensity = Math.abs(velocityValue);
                tooltipContent += `<div style="color: #8B5CF6;">Velocity ${velocityDirection}: ${velocityValue.toFixed(3)}</div>`;
            }
            
            tooltip.innerHTML = tooltipContent;
            tooltip.style.display = 'block';
            tooltip.style.left = Math.min(param.point.x + 10, container.clientWidth - 220) + 'px';
            tooltip.style.top = Math.max(param.point.y - 80, 10) + 'px';
        };

        const hideTooltip = () => {
            if (tooltip) tooltip.style.display = 'none';
        };

        chartRef.current.subscribeCrosshairMove(showTooltip);
        container.addEventListener('mouseleave', hideTooltip);

        return () => {
            if (tooltip && container.contains(tooltip)) {
                container.removeChild(tooltip);
            }
            container.removeEventListener('mouseleave', hideTooltip);
        };
    }, [showWhale, showShark, showRetail, showEMA, showVelocity, emaPeriod, velocityPeriod, selectedMetric]);

    const handleEmaPeriodChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const value = parseInt(e.target.value);
        if (value >= 1 && value <= 200) {
            setEmaPeriod(value);
        }
    };

    const handleEmaPeriodBlur = (e: React.FocusEvent<HTMLInputElement>) => {
        const value = parseInt(e.target.value);
        if (isNaN(value) || value < 1) {
            setEmaPeriod(14);
        } else if (value > 200) {
            setEmaPeriod(200);
        }
    };

    const handleVelocityPeriodChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const value = parseInt(e.target.value);
        if (value >= 1 && value <= 50) {
            setVelocityPeriod(value);
        }
    };

    const handleVelocityPeriodBlur = (e: React.FocusEvent<HTMLInputElement>) => {
        const value = parseInt(e.target.value);
        if (isNaN(value) || value < 1) {
            setVelocityPeriod(3);
        } else if (value > 50) {
            setVelocityPeriod(50);
        }
    };

    const getMetricDescription = (metric: string) => {
        switch (metric) {
            case 'impressions':
                return 'Total views generated by this tier';
            case 'engagement':
                return 'Total weighted engagement score from this tier';
            case 'volume':
                return 'Number of tweets from this tier';
            default:
                return '';
        }
    };

    return (
        <div style={{ width: '100%', height: '400px' }}>
            {/* Legend Controls */}
            <div style={{ 
                display: 'flex', 
                gap: '16px', 
                marginBottom: '8px',
                padding: '8px',
                backgroundColor: '#1f2937',
                borderRadius: '4px',
                flexWrap: 'wrap',
                alignItems: 'center'
            }}>
                <label style={{ display: 'flex', alignItems: 'center', gap: '4px', cursor: 'pointer' }}>
                    <input
                        type="checkbox"
                        checked={showWhale}
                        onChange={(e) => setShowWhale(e.target.checked)}
                    />
                    <span style={{ 
                        width: '12px', 
                        height: '12px', 
                        backgroundColor: '#3B82F6', 
                        display: 'inline-block',
                        marginRight: '4px'
                    }}></span>
                    Whale
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: '4px', cursor: 'pointer' }}>
                    <input
                        type="checkbox"
                        checked={showShark}
                        onChange={(e) => setShowShark(e.target.checked)}
                    />
                    <span style={{ 
                        width: '12px', 
                        height: '12px', 
                        backgroundColor: '#10B981', 
                        display: 'inline-block',
                        marginRight: '4px'
                    }}></span>
                    Shark
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: '4px', cursor: 'pointer' }}>
                    <input
                        type="checkbox"
                        checked={showRetail}
                        onChange={(e) => setShowRetail(e.target.checked)}
                    />
                    <span style={{ 
                        width: '12px', 
                        height: '12px', 
                        backgroundColor: '#F59E0B', 
                        display: 'inline-block',
                        marginRight: '4px'
                    }}></span>
                    Retail
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: '4px', cursor: 'pointer' }}>
                    <input
                        type="checkbox"
                        checked={showEMA}
                        onChange={(e) => setShowEMA(e.target.checked)}
                    />
                    <span style={{ 
                        width: '12px', 
                        height: '2px', 
                        backgroundColor: '#EF4444', 
                        display: 'inline-block',
                        marginRight: '4px'
                    }}></span>
                    EMA ({emaPeriod})
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: '4px', cursor: 'pointer' }}>
                    <input
                        type="checkbox"
                        checked={showVelocity}
                        onChange={(e) => setShowVelocity(e.target.checked)}
                    />
                    <span style={{ 
                        width: '12px', 
                        height: '2px', 
                        backgroundColor: '#8B5CF6', 
                        display: 'inline-block',
                        marginRight: '4px'
                    }}></span>
                    Velocity ({velocityPeriod})
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: '4px', cursor: 'pointer' }}>
                    <input
                        type="checkbox"
                        checked={isPaused}
                        onChange={(e) => setIsPaused(e.target.checked)}
                    />
                    <span style={{ 
                        width: '16px', 
                        height: '12px', 
                        backgroundColor: isPaused ? '#EF4444' : '#10B981', 
                        display: 'inline-block',
                        marginRight: '4px'
                    }}></span>
                    Pause Data Fetching
                </label>
                
                {/* Metric Selection */}
                <button
                    onClick={() => setShowMetricSettings(!showMetricSettings)}
                    style={{
                        background: 'transparent',
                        border: '1px solid #374151',
                        color: '#D1D5DB',
                        padding: '4px 8px',
                        borderRadius: '4px',
                        fontSize: '12px',
                        cursor: 'pointer',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px'
                    }}
                >
                    📊 Metric: {selectedMetric.charAt(0).toUpperCase() + selectedMetric.slice(1)}
                </button>

                {/* EMA Settings Toggle */}
                <button
                    onClick={() => setShowEmaSettings(!showEmaSettings)}
                    style={{
                        background: 'transparent',
                        border: '1px solid #374151',
                        color: '#D1D5DB',
                        padding: '4px 8px',
                        borderRadius: '4px',
                        fontSize: '12px',
                        cursor: 'pointer',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px'
                    }}
                >
                    ⚙️ EMA Settings
                </button>

                {!isLoaded && (
                    <div style={{ 
                        marginLeft: 'auto',
                        fontSize: '12px',
                        color: '#6B7280',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px'
                    }}>
                        <div style={{
                            width: '12px',
                            height: '12px',
                            border: '2px solid #E5E7EB',
                            borderTop: '2px solid #3B82F6',
                            borderRadius: '50%',
                            animation: 'spin 1s linear infinite'
                        }}></div>
                        Loading...
                    </div>
                )}
            </div>

            {/* Metric Settings Panel */}
            {showMetricSettings && (
                <div style={{
                    marginBottom: '8px',
                    padding: '12px',
                    backgroundColor: '#374151',
                    borderRadius: '4px',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '12px'
                }}>
                    <div style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '12px',
                        flexWrap: 'wrap'
                    }}>
                        <label style={{ 
                            color: '#D1D5DB',
                            fontSize: '14px',
                            fontWeight: 'bold'
                        }}>
                            Select Metric:
                        </label>
                        {(['impressions', 'engagement', 'volume'] as const).map(metric => (
                            <label key={metric} style={{
                                display: 'flex',
                                alignItems: 'center',
                                gap: '6px',
                                cursor: 'pointer',
                                color: '#D1D5DB',
                                fontSize: '14px'
                            }}>
                                <input
                                    type="radio"
                                    name="metric"
                                    value={metric}
                                    checked={selectedMetric === metric}
                                    onChange={(e) => setSelectedMetric(e.target.value as typeof selectedMetric)}
                                />
                                {metric.charAt(0).toUpperCase() + metric.slice(1)}
                            </label>
                        ))}
                    </div>
                    <div style={{
                        fontSize: '12px',
                        color: '#9CA3AF',
                        fontStyle: 'italic'
                    }}>
                        {getMetricDescription(selectedMetric)}
                    </div>
                </div>
            )}

            {/* EMA Settings Panel */}
            {showEmaSettings && (
    <div style={{
        marginBottom: '8px',
        padding: '12px',
        backgroundColor: '#374151',
        borderRadius: '4px',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px'
    }}>
        {/* EMA Period Setting */}
        <div style={{
            display: 'flex',
            alignItems: 'center',
            gap: '12px',
            flexWrap: 'wrap'
        }}>
            <label style={{ 
                color: '#D1D5DB',
                fontSize: '14px',
                fontWeight: 'bold',
                minWidth: '100px'
            }}>
                EMA Period:
            </label>
            <input
                type="number"
                value={emaPeriod}
                onChange={handleEmaPeriodChange}
                onBlur={handleEmaPeriodBlur}
                min="1"
                max="200"
                style={{
                    background: '#1F2937',
                    border: '1px solid #4B5563',
                    color: '#D1D5DB',
                    padding: '4px 8px',
                    borderRadius: '4px',
                    fontSize: '14px',
                    width: '80px'
                }}
            />
            <span style={{ 
                color: '#9CA3AF',
                fontSize: '12px'
            }}>
                (1-200 periods)
            </span>
        </div>

        {/* Velocity Period Setting */}
        <div style={{
            display: 'flex',
            alignItems: 'center',
            gap: '12px',
            flexWrap: 'wrap'
        }}>
            <label style={{ 
                color: '#D1D5DB',
                fontSize: '14px',
                fontWeight: 'bold',
                minWidth: '100px'
            }}>
                Velocity Period:
            </label>
            <input
                type="number"
                value={velocityPeriod}
                onChange={handleVelocityPeriodChange}
                onBlur={handleVelocityPeriodBlur}
                min="1"
                max="50"
                style={{
                    background: '#1F2937',
                    border: '1px solid #4B5563',
                    color: '#D1D5DB',
                    padding: '4px 8px',
                    borderRadius: '4px',
                    fontSize: '14px',
                    width: '80px'
                }}
            />
            <span style={{ 
                color: '#9CA3AF',
                fontSize: '12px'
            }}>
                (1-50 periods)
            </span>
        </div>

        {/* Help Text */}
        <div style={{
            fontSize: '12px',
            color: '#9CA3AF',
            fontStyle: 'italic',
            backgroundColor: '#1F2937',
            padding: '8px',
            borderRadius: '4px',
            borderLeft: '3px solid #3B82F6'
        }}>
            <div style={{ marginBottom: '4px' }}>
                <strong>EMA Period:</strong> Number of periods for exponential moving average calculation. 
                Higher values create smoother trends but with more lag.
            </div>
            <div>
                <strong>Velocity Period:</strong> Number of periods to calculate rate of change in EMA. 
                Lower values show more sensitive momentum changes.
            </div>
        </div>

        {/* Quick Preset Buttons */}
        <div style={{
            display: 'flex',
            gap: '8px',
            flexWrap: 'wrap',
            alignItems: 'center'
        }}>
            <span style={{ 
                color: '#D1D5DB',
                fontSize: '12px',
                fontWeight: 'bold'
            }}>
                Quick Presets:
            </span>
            <button
                onClick={() => { setEmaPeriod(7); setVelocityPeriod(2); }}
                style={{
                    background: '#1F2937',
                    border: '1px solid #4B5563',
                    color: '#D1D5DB',
                    padding: '4px 8px',
                    borderRadius: '4px',
                    fontSize: '11px',
                    cursor: 'pointer'
                }}
            >
                Fast (7,2)
            </button>
            <button
                onClick={() => { setEmaPeriod(14); setVelocityPeriod(3); }}
                style={{
                    background: '#1F2937',
                    border: '1px solid #4B5563',
                    color: '#D1D5DB',
                    padding: '4px 8px',
                    borderRadius: '4px',
                    fontSize: '11px',
                    cursor: 'pointer'
                }}
            >
                Medium (14,3)
            </button>
            <button
                onClick={() => { setEmaPeriod(21); setVelocityPeriod(5); }}
                style={{
                    background: '#1F2937',
                    border: '1px solid #4B5563',
                    color: '#D1D5DB',
                    padding: '4px 8px',
                    borderRadius: '4px',
                    fontSize: '11px',
                    cursor: 'pointer'
                }}
            >
                Slow (21,5)
            </button>
        </div>
    </div>
)}

{/* Chart Container */}
<div ref={chartContainerRef} style={{ width: '100%', height: '100%' }} />

{/* Loading Animation CSS */}
<style>
    {`
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
    `}
</style>
            
</div>
    );
};

export default TieredImpressionChart;